c For testing of hypoe2k, strip off the 19 or 20 from the summary
c records generated by hypoe2k to compare with hypoe.
c This program can be run on summary or archive files.
	character*117 record
20	read(5, '(a)', end=90) record
	if(record(83:83) .eq. '/') then
	  write(6, '(a)') record(3:lentru(record))
	else
	  write(6, '(a)') record(1:lentru(record))
	endif
	goto 20
90	stop
	end
c     FINDS THE TRUE LENGTH OF A CHARACTER VARIABLE
      integer function lentru(alph)
      character alph*(*)
      l = len(alph)
      do 100 i = l, 1, -1
      if ((alph(i:i) .ne. ' ') .and. 
     *    (alph(i:i) .ne. '\0')) goto 200
  100 continue
  200 lentru = i
      return 
      end
