C LENTRU.FOR
      INTEGER FUNCTION LENTRU(ALPH)
C     FINDS THE TRUE LENGTH OF A CHARACTER VARIABLE
      CHARACTER ALPH*(*)
      L = LEN(ALPH)
      DO 100 I = L, 1, -1
       IF(ALPH(I:I).NE.' ' .AND. ALPH(I:I).NE.'\0') THEN
         LENTRU = I
         RETURN
        ENDIF
100   CONTINUE
      LENTRU = 0
      RETURN
      END
C END LENTRU
